export { Logo } from "./Logo";
export { Check } from "./Check";
export { BigLogo } from "./BigLogo";
export { ApplePay } from "./ApplePay";
export { PayPal } from "./PayPal";
export { Bitcoin } from "./Bitcoin";
export { Shevron } from "./Shevron";
export { Trash } from "./Trash";
export { RoundCheck } from "./RoundCheck";
